import subprocess
import openai
import re
from utils import common, constants
from PyQt5.QtCore import QObject, pyqtSignal, pyqtSlot
from api.proof_worker import ProofWorker

class ProofVerificationAPI(QObject):
    """
    The ProofVerificationAPI class is responsible for generating and verifying
    mathematical proofs using OpenAI's ChatGPT and Agda.
    """
    proof_result = pyqtSignal(bool, str, str)
    progress_update = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.worker = None


    @pyqtSlot(str)
    def generate_and_verify_proof(self, statement):
        """
        Generates a proof for the given mathematical statement and verifies it using Agda.
        If the proof is invalid, it refines the proof iteratively until a valid one is found.
        """
        self.worker = ProofWorker(self, statement)
        self.worker.proof_result.connect(self.proof_result.emit)
        self.worker.progress_update.connect(self.progress_update.emit)
        self.worker.run()


    def generate_proof_with_chatgpt(self, statement):
        """
        Generates a formal proof in Agda using ChatGPT for the given statement.
        """
        prompt = (f"Generate a formal proof in Agda for the following statement: "
                  f"'{statement}'. \n Only output the Agda code. Do not use libraries. Do not include comments, explanations, or any additional text.")
        response = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a mathematical proof generator. Provide proofs in Agda syntax."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content

    def verify_with_agda(self, proof):
        """
        Verifies the given Agda proof using the Agda type-checker.
         """
        proof = self.clean_agda_code(proof)
        # Write proof to a temporary file
        with open("temp_proof.agda", "w", encoding='utf-8') as f:
            f.write(proof)
        # Run Agda type-checker
        exit_code, feedback = common.run_command("agda temp_proof.agda", True)
        is_valid = True if exit_code == 0 else False
        return is_valid, feedback

    def refine_proof_with_chatgpt(self, statement, previous_proof, feedback):
        """
        Refines the given Agda proof based on feedback using ChatGPT.
        """
        prompt = f"""
        Refine the following Agda proof for the statement: '{statement}'
        Only provide the Agda code—no explanations or additional text.

        Previous proof:
        {previous_proof}

        Agda feedback:
        {feedback}

        Provide an improved Agda proof.
        """
        response = openai.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a mathematical proof generator. Provide proofs in Agda syntax."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content

    def clean_agda_code(self, raw_code):
        """
        Cleans the Agda code generated by ChatGPT by removing:
        - Markdown code block formatting (backticks)
        - Any module declaration
        - Comments (starting with '--')
        """
        # Remove Markdown code block formatting (```)
        clean_code = raw_code.replace("```agda", "").replace("```", "").strip()

        # Remove module declaration (if any) and anything before the first piece of Agda code
        clean_code = re.sub(r'.*(?=data|module)', '', clean_code, flags=re.DOTALL).strip()

        # Remove comments (lines starting with '--')
        clean_code = re.sub(r'--.*\n', '', clean_code)

        return clean_code
